src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Cocur\Slugify\Slugify;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{
    public const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(mimeTypes="image/jpeg")
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;


    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="5")
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min="10", max="400")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $romms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^\d{5}/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default":false})
     */
    private $sold;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EntityOption", inversedBy="properties")
     */
    private $entityOption;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRomms(): ?int
    {
        return $this->romms;
    }

    public function setRomms(int $romms): self
    {
        $this->romms = $romms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormatedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getHeadInfos()
    {
        return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }


    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->sold = false;
        $this->entityOption = new ArrayCollection();
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|EntityOption[]
     */
    public function getEntityOption(): Collection
    {
        return $this->entityOption;
    }

    public function addEntityOption(EntityOption $entityOption): self
    {
        if (!$this->entityOption->contains($entityOption)) {
            $this->entityOption[] = $entityOption;
            $entityOption->addProperty($this);
        }

        return $this;
    }

    public function removeEntityOption(EntityOption $entityOption): self
    {
        if ($this->entityOption->contains($entityOption)) {
            $this->entityOption->removeElement($entityOption);
            $entityOption->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return null|string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * @param null|string $filename
     * @return Property
     */
    public function setFilename($filename)
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param mixed $imageFile
     * @return Property
     * @throws \Exception
     */
    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;

        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\EntityOption;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('romms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' =>  array_flip(Property::HEAT)
            ])
            ->add('entityOption', EntityType::class, [
                'class' =>  EntityOption::class,
                'choice_label' =>  'name',
                'multiple' =>  true
            ])
            ->add('imageFile', FileType::class, [
                'required' =>  false,
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/PropertyController.php
<?php

/**
 * Created by PhpStorm.
 * User: toure
 * Date: 04/09/2019
 * Time: 10:58
 */

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;
    private $em;

    public function __construct(PropertyRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @return PropertyRepository
     */
    public function getRepository(): PropertyRepository
    {
        return $this->repository;
    }

    /**
     * @param PropertyRepository $repository
     */
    public function setRepository(PropertyRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/biens", name="property.index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */

    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $property = $paginator->paginate(
            $this->repository->findAllVisible($search),
            $request->query->getInt('page', 1),
            6
        );

        return $this->render('property/index.html.twig', [
            'property' => $property,
            'current_menu' => 'properties',
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug"="[a-z0-9\-]*"})
     * @param Property $property
     * @param string $slug
     * @param Request $request
     * @param ContactNotification $notification
     * @return Response
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $notification): Response
    {
        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if($property->getSlug() !== $slug)
        {
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug(),
            ], 301);
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $notification->notify($contact);
            $this->addFlash('success', 'Merci de nous avoir contacté !');
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug(),
            ]);
        }

        return $this->render('property/show.html.twig', [
            'property' => $property,
            'form' => $form->createView()
        ]);
    }
}

templates/property/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'Liste des biens' %}
{% block body %}
    <div class="container">
        <h1>Tous les biens</h1>

        <div class="jumbotron">
            {{ include('property/partial/_searchForm.html.twig', {button:'Rechercher'}) }}
        </div>

        <div class="row">
            {% for entity in property %}
                {{ include('property/partial/_property.html.twig') }}
            {% endfor %}
        </div>

        <div class="navigation m-3 text-center">
            {{ knp_pagination_render(property) }}
        </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}
{% block title 'Bien' %}
{% block body %}
    <h1>{{ property.title }}</h1>
    <p> {{ property.description }}</p>
    <div class="container">
        <div class="row">
            {% for message in app.flashes('success') %}
                <p class="alert alert-success">
                    {{ message }}
                </p>
            {% endfor %}
            <div class="col-12 col-md-4">
                <div>
                    {% if property.filename %}
                        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt="{{ property.filename }}">
                    {% else %}
                        <img src="{{ '/images/proprieties/placeholder.jpg' | imagine_filter('medium') }}" alt="">
                    {% endif %}
                </div>
                {% if property.entityOption|length %}
                    <div class="my-5 col-12 col-md-6 ml-0 pl-0">
                        <ul>
                            {% for option in property.entityOption %}
                                <li class="badge badge-pill badge-secondary">{{ option.name }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
            <div class="col-12 col-md-8 d-flex justify-content-between flex-column">
                <div>
                    <div>
                        <p class="d-inline-block">{{ property.city }}</p>,
                        <p class="badge badge-pill badge-success d-inline-block vertical-align-center">
                            Prix: {{ property.formatedPrice }} €
                        </p>
                    </div>
                    <div>
                        <table class="table">
                            <tr>
                                <td>surface</td>
                                <td>{{ property.surface }}</td>
                            </tr>
                            <tr>
                                <td>Pièces</td>
                                <td>{{ property.romms }}</td>
                            </tr>
                            <tr>
                                <td>Chambres</td>
                                <td>{{ property.bedrooms }}</td>
                            </tr>
                            <tr>
                                <td>Etage</td>
                                <td>{{ property.floor }}</td>
                            </tr>

                            <tr>
                                <td>surface</td>
                                <td>{{ property.surface }}</td>
                            </tr>
                            <tr>
                                <td>Pièces</td>
                                <td>{{ property.romms }}</td>
                            </tr>
                            <tr>
                                <td>Chambres</td>
                                <td>{{ property.bedrooms }}</td>
                            </tr>
                            <tr>
                                <td>Etage</td>
                                <td>{{ property.floor }}</td>
                            </tr>
                            <tr>
                                <td>Code Postal</td>
                                <td>{{ property.postalCode }}</td>
                            </tr>
                            <tr>
                                <td>Chauffage</td>
                                <td>{{ property.HeadInfos }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            {{ form_start(form) }}
            <div class="row">
                <div class="col-md-4"> {{ form_row(form.firstName) }}</div>
                <div class="col-md-4">{{ form_row(form.lastName) }}</div>
            </div>

            <div class="row">
                <div class="col-md-4"> {{ form_row(form.phone) }}</div>
                <div class="col-md-4"> {{ form_row(form.email) }}</div>
            </div>

            <div class="row">
                <div class="col-md-12">{{ form_row(form.message) }}</div>
            </div>

            {{ form_rest(form) }}
            <button class="btn btn-primary">{{ button|default('Contacter l\'agence') }}</button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}